<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class NovosItensSeeder extends Seeder
{
    public function run(): void
    {
        $itens = array_merge(
            $this->itensPdf(),
            $this->itensDescartaveis(),
            $this->itensEstocaveis(),
            $this->itensProteina()
        );

        $inseridos = 0;
        $duplicados = 0;

        foreach ($itens as $item) {
            $existe = DB::table('itens')->where('codigo', $item['codigo'])->exists();

            if ($existe) {
                $duplicados++;
                continue;
            }

            DB::table('itens')->insert([
                'id' => Str::uuid()->toString(),
                'codigo' => $item['codigo'],
                'referencia' => $item['referencia'] ?? '',
                'nome' => $item['nome'],
                'tipo' => $item['tipo'],
            ]);

            $inseridos++;
        }

        $this->command->info("Inseridos: {$inseridos} | Duplicados (ignorados): {$duplicados}");
    }

    private function itensPdf(): array
    {
        return [
            ['codigo' => '6', 'nome' => 'AROMATIZANTE DE AR 360ML - FRASCO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '36', 'nome' => 'DISCO PRETO PESADO 350', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '37', 'nome' => 'ESCOVA DE NYLON P/VASO SANITARIO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '38', 'nome' => 'ESPONJA DUPLA FACE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '39', 'nome' => 'FIBRA PARA LIMPEZA LEVE BRANCA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '40', 'nome' => 'FIBRAÇO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '48', 'nome' => 'PASTA BRANCA LIMPITEC POTE C/500GR', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '64', 'nome' => 'PANO DE CHAO ALVEJADO 70X50', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '74', 'nome' => 'PAPEL TOALHA INTERFOLHA - FARDO C/1000 FOLHAS', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '83', 'nome' => 'DESENTUPIDOR DE PIA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '85', 'nome' => 'DESENTUPIDOR DE VASO SANITARIO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '88', 'nome' => 'LUSTRA MOVEL PEQUENO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '94', 'nome' => 'VASSOURA DOMESTICA DE NYLON', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '97', 'nome' => 'VASSOURA PIAÇAVA GARI PADRÃO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1056', 'nome' => 'PERFEX 30 X 300M', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1107', 'nome' => 'COLHER DESCARTAVEL REFORÇADA - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1109', 'nome' => 'COPO DESCARTAVEL 200ML - PACOTE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1110', 'nome' => 'COPO DESCARTAVEL 300ML - PACOTE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1116', 'nome' => 'FACA DESCARTAVEL REFORÇADA - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1119', 'nome' => 'GARFO DESCARTAVEL REFORÇADO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1121', 'nome' => 'GUARDANAPO BRANCO 22X22 - CAIXA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1125', 'nome' => 'PALITO DE DENTE EMBALADO - CAIXA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1126', 'nome' => 'PALITO CHURRASCO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1128', 'nome' => 'COPO DESCARTAVEL 100ML - CAIXA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1130', 'nome' => 'TAMPA DESCARTAVEL 300ML - PACOTE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1131', 'nome' => 'TAMPA DESCARTAVEL 100ML - CAIXA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11403', 'nome' => 'CANUDO FLEXIVEL EMBALADO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11518', 'nome' => 'PAPEL ALUMINIO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11634', 'nome' => 'DETERGENTE 500ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11671', 'nome' => 'SABONETE LIQUIDO REFIL ERVA DOCE 800ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '14201', 'nome' => 'INSETICIDA AEROSOL 380ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '14554', 'nome' => 'LUVAS ANTI DERRAPANTE G AMARELA - PAR', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '14555', 'nome' => 'LUVAS ANTI DERRAPANTE G VERDE - PAR', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '14927', 'nome' => 'VASSOURA PIAÇAVA COMUM USO NO COLEGIO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '15216', 'nome' => 'KIT DESJEJUM - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '15272', 'nome' => 'KIT ALMOÇO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '16055', 'nome' => 'HIPOCLORETO DE SODIO 1% GALAO DE 5LT', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '16565', 'nome' => 'PAPEL TOALHA BOBINA AUTO CORTE FARDO C/ 6 200MT', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '16775', 'nome' => 'PAPEL HIG. INTERFOLHA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '18372', 'nome' => 'PEDRA SANITARIA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '18714', 'nome' => 'DISCO PRETO PESADO 410', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24954', 'nome' => 'SOPEIRA ISOPOR 300ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24955', 'nome' => 'MARMITA ISOPOR 4 CAVIDADES - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24967', 'nome' => 'TAMPA ISOPOR 180ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24988', 'nome' => 'COPO ISOPOR 300ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24989', 'nome' => 'TAMPA ISOPOR 300ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25058', 'nome' => 'MEXEDOR DE SUCO - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25269', 'nome' => 'POTE QUADRADO 200ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25433', 'nome' => 'DISCO VERDE 410MM', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26021', 'nome' => 'COPO ISOPOR 180ML - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26078', 'nome' => 'KIT PASTOSA - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26079', 'nome' => 'QUENTINHA GRANDE FUNDA - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26083', 'nome' => 'PAPEL TOALHA C/2 ROLOS - UNIDADE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26112', 'nome' => 'COPO DESCARTAVEL 50ML - PACOTE', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '27124', 'nome' => 'SABONETE PEROLADO 15G', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '27857', 'nome' => 'COLHER DESCARTÁVEL DE SOBREMESA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '27939', 'nome' => 'BORRIFADOR TRANSPARENTE 500ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '27940', 'nome' => 'FILME PVC 28X300M', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28101', 'nome' => 'FIBRA PARA LIMPEZA PESADA - VERDE 102MMX260MM', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28111', 'nome' => 'PAPEL HIGIENICO ROLÃO 300MT C/8', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28116', 'nome' => 'BOBINA PICOTADA 30 CM X 40 CM', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28117', 'nome' => 'BOBINA PICOTADA 40 CM X 60 CM', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28124', 'nome' => 'ALCOOL SUPERFICIE 70% GARRAFA 1 LITRO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28125', 'nome' => 'SACO DE LIXO AZUL DE 200L PCT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28129', 'nome' => 'SACO DE LIXO PRETO 250 LTS PCT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28131', 'nome' => 'SACO DE LIXO TRANSPARENTE 200 LTS PACT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28132', 'nome' => 'SACO DE LIXO VERDE 100 LTS PCT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28133', 'nome' => 'SACO DE LIXO VERDE 60 LTS PCT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28445', 'nome' => 'PAPEL HIGIENICO ROLÃO NOBREPAPER STYLE 250M DIRET.', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28679', 'nome' => 'ALCOOL GEL 5L', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '28730', 'nome' => 'PAPEL HIGIENICO FOLHA DUPLA ROLO 30MT', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29281', 'nome' => 'ALCOOL EM GEL 70 - REFIL 800ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29282', 'nome' => 'ESCOVA DE PLASTICO PARA CANTO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29401', 'nome' => 'CERA SUPER WAX HS 04 TOP', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29402', 'nome' => 'REMOVEDOR REMOVIT WAX SUPER', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29403', 'nome' => 'BECKER FLOWER PITANGA NEGRA', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29458', 'nome' => 'DISCO VERDE 350', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '29468', 'nome' => 'BECKER PEROX ADVANCED DESINFETANTE HOSPITALAR', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30050', 'nome' => 'CLEAN GLASE - GALÃO 5L', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30051', 'nome' => 'REMOVIC 750ML', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30052', 'nome' => 'SACO TRANSPARENTE 18X25', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30053', 'nome' => 'SACO TRANSPARENTE 30X40', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30054', 'nome' => 'SACO TRANSPARENTE 50X70', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30055', 'nome' => 'SACO TRANSPARENTE 60X90', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30056', 'nome' => 'SACO DE LIXO INFECTANTE BRANCO DE 100L PCT C/100', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30057', 'nome' => 'STAR GLASS GALÃO 5LTS MULT USO', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30058', 'nome' => 'VULCAN FLORAL - GALÃO 5L', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30059', 'nome' => 'VASELINA LIQUIDA LT', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30060', 'nome' => 'PAPEL HIGIENICO FOLHA DUPLA ROLO 30MT', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '30061', 'nome' => 'PASTA BRANCA LIMPITEC - POTE 500GR', 'tipo' => 'MAT. LIMPEZA E DESCARTAVEIS', 'referencia' => ''],
        ];
    }

    private function itensDescartaveis(): array
    {
        return [
            ['codigo' => '1110', 'nome' => 'COPO DESCARTÁVEL 300ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1109', 'nome' => 'COPO DESCARTÁVEL 200ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1128', 'nome' => 'COPO DESCARTÁVEL 100ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26112', 'nome' => 'COPO DESCARTÁVEL 50ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1130', 'nome' => 'TAMPA DESCARTÁVEL 300ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1131', 'nome' => 'TAMPA DESCARTÁVEL 100ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26021', 'nome' => 'COPO ISOPOR 180ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24988', 'nome' => 'COPO ISOPOR 300ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24967', 'nome' => 'TAMPA ISOPOR 180ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24989', 'nome' => 'TAMPA ISOPOR 300ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '10764', 'nome' => 'REFIL 5 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '15205', 'nome' => 'REFIL 4 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1095', 'nome' => 'REFIL SOPA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '749', 'nome' => 'SACO PLÁSTICO P/ PÃO - 15X25', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1121', 'nome' => 'GUARDANAPO BRANCO 22X22', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '19724', 'nome' => 'GUARDANAPO CREPADO 14X14', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '23645', 'nome' => 'MEXEDOR DE SUCO (240UND)', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26078', 'nome' => 'KIT PASTOSA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '15272', 'nome' => 'KIT ALMOÇO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '15216', 'nome' => 'KIT DESJEJUM', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '16319', 'nome' => 'QUENTINHA RETANGULAR 3 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11403', 'nome' => 'CANUDO FLEXÍVEL EMBALADO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1126', 'nome' => 'PALITO CHURRASCO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1125', 'nome' => 'PALITO DENTE EMBALADO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26080', 'nome' => 'PAPEL BANDEJA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1119', 'nome' => 'GARFO DESCARTÁVEL REFORÇADO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1116', 'nome' => 'FACA DESCARTÁVEL REFORÇADA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '1107', 'nome' => 'COLHER DESCARTÁVEL REFORÇADA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24966', 'nome' => 'MARMITA ISOPOR 1 CAVIDADE (DESJEJUM)', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25056', 'nome' => 'MARMITA ISOPOR 3 CAVIDADES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25322', 'nome' => 'COPO DESCARTÁVEL 160ML (MÁQUINA DE CAFÉ)', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '353', 'nome' => 'FILME PVC 300M', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26086', 'nome' => 'REFIL TAMPA 5 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26111', 'nome' => 'QUENTINHA RETANGULAR 4 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26085', 'nome' => 'REFIL TAMPA 4 DIVISÕES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '12760', 'nome' => 'REFIL TAMPA SOPA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24955', 'nome' => 'MARMITA ISOPOR 4 CAVIDADES', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26083', 'nome' => 'PAPEL TOALHA C/ 2 ROLOS', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '11518', 'nome' => 'PAPEL ALUMÍNIO', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25281', 'nome' => 'MALETA ANIVERSARIANTE', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '25269', 'nome' => 'POTE QUADRADO 200ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26084', 'nome' => 'TAMPA P/ POTE QUADRADO 200ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26079', 'nome' => 'QUENTINHA GRANDE FUNDA', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '747', 'nome' => 'SACO PLÁSTICO P/ TALHER - 8X25', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '17449', 'nome' => 'SACOLA DE RÁFIA 50X60', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '24954', 'nome' => 'SOPEIRA ISOPOR 300ML', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
            ['codigo' => '26081', 'nome' => 'BOBINA P/ AÇOUGUE 7,3KG', 'tipo' => 'DESCARTAVEIS', 'referencia' => ''],
        ];
    }

    private function itensEstocaveis(): array
    {
        return [
            ['codigo' => '25837', 'nome' => 'ABACAXI EM CALDAS LATA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19593', 'nome' => 'ACHOCOLATADO EM PÓ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18798', 'nome' => 'AÇÚCAR CRISTAL', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25747', 'nome' => 'AÇÚCAR REFINADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25748', 'nome' => 'AÇÚCAR SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25749', 'nome' => 'ADOÇANTE LÍQUIDO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25750', 'nome' => 'ADOÇANTE SUCRALOSE SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '15376', 'nome' => 'ÁGUA DE COCO TP C/ 200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18', 'nome' => 'ÁGUA MINERAL GF 1,5L', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17221', 'nome' => 'ÁGUA MINERAL GF 500ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19595', 'nome' => 'AMEIXA EM CALDAS', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '113', 'nome' => 'AMENDOIM INATURA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '112', 'nome' => 'AMEIXA SECA S/CAROÇO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25751', 'nome' => 'AMIDO DE MILHO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25752', 'nome' => 'ARROZ AGULINHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25753', 'nome' => 'ARROZ INTEGRAL', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '124', 'nome' => 'ATUM RALADO EM CONSERVA LT C/ 170G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25754', 'nome' => 'ARROZ PARBOLIZADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '125', 'nome' => 'AVEIA EM FLOCOS FINOS PACOTE C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19594', 'nome' => 'AZEITE DE OLIVA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25755', 'nome' => 'AZEITE DE OLIVA 500ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25756', 'nome' => 'AZEITONA PRETA BALDE C/2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19510', 'nome' => 'AZEITONA PRETA VIDRO C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25757', 'nome' => 'AZEITONA VERDE BALDE C/ 2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19511', 'nome' => 'AZEITONA VERDE VIDRO C/ 500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '15235', 'nome' => 'BATATA PALHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20396', 'nome' => 'BISCOITO ÁGUA INDIVIDUAL SACHE C/2', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25838', 'nome' => 'BISCOITO CREAM CRACKER PACOTE C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25692', 'nome' => 'BISCOITO CREAM CRACKER INDIVIDUAL SACHE C/4', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25759', 'nome' => 'BISCOITO MAISENA PACOTE C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25693', 'nome' => 'BISCOITO MARIA INDIVIDUAL SACHE C/5', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '151', 'nome' => 'BISCOITO MARIA PACOTE C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25761', 'nome' => 'BISCOITO AMANTEIGADO DE LEITE SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25694', 'nome' => 'BISCOITO AMANTEIGADO DE CHOCOLATE SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '23521', 'nome' => 'BISCOITO WAFFER SABORES DIVERSOS 90G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '154', 'nome' => 'BISCOITO RECHEADO SABORES DIVERSOS 90G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '16799', 'nome' => 'CACAU EM PÓ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25860', 'nome' => 'CAFÉ MELITA TRADICIONAL PCT C/1KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25762', 'nome' => 'CALDO DE CARNE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '168', 'nome' => 'CALDO DE GALINHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20341', 'nome' => 'CALDO DE CAMARÃO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '172', 'nome' => 'CANJICA BRANCA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25763', 'nome' => 'CANELA EM CASCA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25764', 'nome' => 'CANELA EM PÓ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25842', 'nome' => 'CARNE VEGETAL MOÍDA LATA C/400G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25777', 'nome' => 'CHÁ MATE PCT C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25778', 'nome' => 'CHÁ DE CAMOMILA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25779', 'nome' => 'CHÁ DE ERVA CIDREIRA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17264', 'nome' => 'CHÁ DE ERVA DOCE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25780', 'nome' => 'CHÁ DE HORTELÃ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25781', 'nome' => 'CHÁ DE MAÇÃ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25782', 'nome' => 'CHÁ PRETO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20342', 'nome' => 'CHAMPIGNON FATIADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25839', 'nome' => 'CHOCOLATE GRANULADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24640', 'nome' => 'COLORAU', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25784', 'nome' => 'COMINHO EM PÓ PACOTE C/500 GR', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '11199', 'nome' => 'COCO RALADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25785', 'nome' => 'CRAVO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25786', 'nome' => 'CREME CHANTILIY PRONTO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '307', 'nome' => 'CREME DE LEITE 200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24641', 'nome' => 'CREME DE CEBOLA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '309', 'nome' => 'CREMOGEMA CX C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '311', 'nome' => 'CURAU', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25787', 'nome' => 'ERVA MATE FARDO C/10KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17229', 'nome' => 'ERVILHA LATA C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25788', 'nome' => 'ERVILHA LATA C/2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25789', 'nome' => 'ERVILHA SECA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17451', 'nome' => 'EXTRATO DE TOMATE LATA C/340G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25126', 'nome' => 'EXTRATO DE TOMATE C/2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25790', 'nome' => 'EXTRATO DE TOMATE LATA C/4KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '354', 'nome' => 'FLAN SABOR BAUNILHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25791', 'nome' => 'FARINHA DE AVEIA CX C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25792', 'nome' => 'FARINHA LÁCTEA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25841', 'nome' => 'FARINHA DE MESA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '334', 'nome' => 'FARINHA DE ROSCA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '335', 'nome' => 'FARINHA DE TRIGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25793', 'nome' => 'FARINHA DE KIBE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '336', 'nome' => 'FEIJÃO BRANCO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17268', 'nome' => 'FEIJÃO CARIOCA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '337', 'nome' => 'FEIJÃO FRADINHO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25794', 'nome' => 'FEIJÃO PRETO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '339', 'nome' => 'FEIJÃO MANTEIGA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '342', 'nome' => 'FERMENTO EM PÓ ROYAL LATA C/250G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '15399', 'nome' => 'FIGO EM CALDAS LATA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25796', 'nome' => 'FUBÁ DE MILHO PACOTE C/1 KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '403', 'nome' => 'GRÃO DE BICO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10756', 'nome' => 'GELATINA DIET SABOR ABACAXI', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19521', 'nome' => 'GELATINA DIET SABOR MARACUJÁ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25797', 'nome' => 'GELATINA DIET SABOR FRAMBOESA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25798', 'nome' => 'GELATINA DIET SABOR LIMÃO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10635', 'nome' => 'GELATINA DIET SABOR MORANGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25799', 'nome' => 'GELATINA DIET SABOR PÊSSEGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19522', 'nome' => 'GELATINA DIET SABOR UVA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '359', 'nome' => 'GELATINA SABOR ABACAXI', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '364', 'nome' => 'GELATINA SABOR CEREJA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '362', 'nome' => 'GELATINA SABOR FRAMBOESA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19527', 'nome' => 'GELATINA SABOR FRUTAS VERMELHAS', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '367', 'nome' => 'GELATINA SABOR LIMÃO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '360', 'nome' => 'GELATINA SABOR MORANGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19526', 'nome' => 'GELATINA SABOR PÊSSEGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19523', 'nome' => 'GELATINA SABOR LARANJA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '358', 'nome' => 'GELATINA SABOR UVA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19525', 'nome' => 'GELATINA SABOR KIWI', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '366', 'nome' => 'GELATINA SABOR TANGERINA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25695', 'nome' => 'GELEIA DIET INDIVIDUAL SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '26553', 'nome' => 'GELEIA COMUM INDIVIDUAL SABORES', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25800', 'nome' => 'GELEIA DE MOCOTO TP C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25939', 'nome' => 'GOIABADA 7KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19509', 'nome' => 'KETCHUP 180G POTE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '413', 'nome' => 'KETCHUP GALÃO C/3.2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25801', 'nome' => 'KETCHUP SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '430', 'nome' => 'LEITE LONGA VIDA INTEGRAL', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '15354', 'nome' => 'LEITE LONGA VIDA DESNATADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19333', 'nome' => 'LEITE ZERO S/ LACTOSE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18864', 'nome' => 'LEITE DE SOJA EM PÓ LATA C/ 300G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25802', 'nome' => 'LEITE CONDENSADO TP', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '426', 'nome' => 'LEITE DE COCO GF C/500ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25803', 'nome' => 'LEITE EM PÓ DESNATADO SACHE 200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '14914', 'nome' => 'LEITE EM PÓ INTEGRAL SACHE 400G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24355', 'nome' => 'LEITE ACHOCOLATADO 200 ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '433', 'nome' => 'LENTILHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25805', 'nome' => 'LOURO EM PÓ PACOTE C/500 G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25806', 'nome' => 'MACARRÃO PADRE NOSSO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '450', 'nome' => 'MACARRÃO ALETRIA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25807', 'nome' => 'MACARRÃO ESPAGUETE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25808', 'nome' => 'MACARRÃO P/LASANHA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25809', 'nome' => 'MACARRÃO PARAFUSO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '15265', 'nome' => 'MACARRÃO PENE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '455', 'nome' => 'MACARRÃO TALHARIN', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18192', 'nome' => 'MAIONESE SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25812', 'nome' => 'MAIONESE POTE C/3KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18139', 'nome' => 'MAIONESE POTE C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '459', 'nome' => 'MANJAR EM PÓ', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25813', 'nome' => 'MANJERICÃO EM FLOCOS PACOTE C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25696', 'nome' => 'MANTEIGA INDIVIDUAL C/SAL SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25821', 'nome' => 'MANTEIGA COM SAL CAIXA C/5KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25697', 'nome' => 'MANTEIGA INDIVIDUAL S/SAL SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18092', 'nome' => 'MARGARINA COM SAL POTE C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25822', 'nome' => 'MARGARINA COM SAL BALDE C/15KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20639', 'nome' => 'MILHO DE PIPOCA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '17224', 'nome' => 'MILHO VERDE LATA C/200G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '466', 'nome' => 'MILHO VERDE LATA C/2KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25825', 'nome' => 'MOLHO INGLÊS GF C/1L', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19613', 'nome' => 'MOLHO SHOYO 180ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25826', 'nome' => 'MOLHO SHOYO GF C/1L', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20240', 'nome' => 'MOLHO BARBECUE BAG C/1.100G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19512', 'nome' => 'MOSTARDA 180G POTE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '471', 'nome' => 'MOSTARDA GALÃO C/3KG', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18191', 'nome' => 'MOSTARDA SACHE CX C/196', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '16316', 'nome' => 'MUCILON ARROZ LATA C/ 400G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19705', 'nome' => 'MUCILON MILHO LATA C/400G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '18713', 'nome' => 'NESCAU LATA C/400G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25827', 'nome' => 'ÓLEO DE SOJA GF C/900ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '475', 'nome' => 'ÓLEO DE SOJA LATÃO C/18 LITROS', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '477', 'nome' => 'OREGANO PACOTE C/500G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10768', 'nome' => 'PUDIM DIET SABOR BAUNILHA CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10769', 'nome' => 'PUDIM DIET SABOR CARAMELO CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10770', 'nome' => 'PUDIM DIET SABOR CHOCOLATE CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25828', 'nome' => 'PUDIM DIET SABOR COCO CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20483', 'nome' => 'PUDIM DIET SABOR LEITE CONDENSADO CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '10771', 'nome' => 'PUDIM DIET SABOR MORANGO CX C/12', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '627', 'nome' => 'PUDIM SABOR BAUNILHA - QUILO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '509', 'nome' => 'PUDIM SABOR CARAMELO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '511', 'nome' => 'PUDIM SABOR CHOCOLATE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '629', 'nome' => 'PUDIM SABOR DE COCO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '507', 'nome' => 'PUDIM SABOR MORANGO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20620', 'nome' => 'PROTEINA DE SOJA ESCURA SABOR CARNE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25691', 'nome' => 'QUEIJO RALADO SACHE C/50G', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25830', 'nome' => 'SAL SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25831', 'nome' => 'SAL GROSSO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25832', 'nome' => 'SAL REFINADO', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19528', 'nome' => 'SUCO / NECTA SABOR CAJÚ TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19533', 'nome' => 'SUCO / NECTA SABOR GOIABA TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19530', 'nome' => 'SUCO / NECTA SABOR LARANJA TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19531', 'nome' => 'SUCO / NECTA SABOR MARACUJÁ TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19532', 'nome' => 'SUCO / NECTA SABOR PÊSSEGO TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19529', 'nome' => 'SUCO / NECTA SABOR UVA TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20621', 'nome' => 'SUCO / NECTA SABOR ABACAXI TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '20535', 'nome' => 'SUCO / NECTA SABOR MANGA TETRAPACK', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24425', 'nome' => 'SUCO / NECTA SABOR LARANJA TP C/200 ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24426', 'nome' => 'SUCO / NECTA SABOR PÊSSEGO TP C/200 ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25843', 'nome' => 'SUCO DE SOJA ADES SABOR LARANJA TP C/200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25833', 'nome' => 'SUCO DE SOJA ADES SABOR MAÇÃ TP C/ 200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19615', 'nome' => 'SUCO DE SOJA ADES SABOR PÊSSEGO TP C/ 200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25844', 'nome' => 'SUCO DE SOJA ADES SABOR UVA TP C/ 200ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '700', 'nome' => 'TAPIOCA GRANULADA', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19622', 'nome' => 'TORRADA INTEGRAL SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25834', 'nome' => 'TORRADA SALGADA SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '718', 'nome' => 'VINAGRE BRANCO GF 750ML', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '19830', 'nome' => 'VINAGRE BRANCO SACHE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '25835', 'nome' => 'UVA PASSAS S/SEMENTES', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '14183', 'nome' => 'XAROPE DE GUARANA GF', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '24639', 'nome' => 'AMACIANTE DE CARNE', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
            ['codigo' => '26523', 'nome' => 'POLENGUINHO LIGHT', 'tipo' => 'ESTOCAVEIS', 'referencia' => ''],
        ];
    }

    private function itensProteina(): array
    {
        return [
            ['codigo' => '28466', 'nome' => 'ALMONDEGAS DE CARNE', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25090', 'nome' => 'BACON EM MANTA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '158', 'nome' => 'BUCHO BOVINO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25706', 'nome' => 'CARNE MOÍDA BOVINA DE PRIMEIRA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25091', 'nome' => 'CARNE SECA LAGARTO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25105', 'nome' => 'CARRÉ SUÍNO FATIADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25092', 'nome' => 'CHÃ DE DENTRO (COXÃO MOLE) BOVINO RESFRIADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '29027', 'nome' => 'COPA LOMBO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25093', 'nome' => 'COSTELA BOVINA FATIADA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '27160', 'nome' => 'COSTELA SUÍNA SALGADA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25094', 'nome' => 'COSTELA SUÍNA FATIADA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '17347', 'nome' => 'DRUMETE DE FRANGO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25095', 'nome' => 'FÍGADO BOVINO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25096', 'nome' => 'FILÉ DE COXA DE FRANGO S/PELE - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25097', 'nome' => 'FILÉ DE FRANGO S/OSSO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25344', 'nome' => 'FILÉ DE PEIXE PANGA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25099', 'nome' => 'HAMBÚRGUER ENVELOPADO BOVINO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25100', 'nome' => 'LAGARTO PLANO BOVINO RESFRIADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25686', 'nome' => 'LAGARTO REDONDO BOVINO RESFRIADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25107', 'nome' => 'LINGUIÇA CALABRESA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25109', 'nome' => 'LINGUIÇA FINA SUÍNA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '20691', 'nome' => 'LINGUIÇA TOSCANA DE FRANGO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25111', 'nome' => 'LINGUIÇA TOSCANA SUÍNA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '16452', 'nome' => 'LOMBO SUÍNO CONGELADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25445', 'nome' => 'LOMBO SUÍNO SALGADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25330', 'nome' => 'PALETA S/ MÚSCULO BOVINA RESFRIADA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '5523', 'nome' => 'PATINHO BOVINO RESFRIADO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '505', 'nome' => 'PRESUNTO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '12082', 'nome' => 'QUEIJO MINAS - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25682', 'nome' => 'QUEIJO MUÇARELA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25683', 'nome' => 'QUEIJO PARMESÃO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '24939', 'nome' => 'RABADA BOVINA FATIADA - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25112', 'nome' => 'SALSICHA DE CARNE - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '25446', 'nome' => 'SOBRECOXA DE FRANGO - QUILO', 'tipo' => 'PROTEINA', 'referencia' => ''],
            ['codigo' => '24353', 'nome' => 'NUGGETS (PACOTE)', 'tipo' => 'PROTEINA', 'referencia' => ''],
        ];
    }
}
